### ISSUE TITLE
Suggestion, buttons to add 5, add 10

### ISSUE THREAD

**Issue by paulovitorbal** [xixilive/jquery-spinner#10]
I will change the code to work as this

<5 <1 [ 0 ] 1> 5>

Something like, add 5 units to field, subtract 10 from field.

**Comment by xixilive** [comment]
you can specify a 'step' options to initialize a spinner object. such as:
```javascript
$('#my-spinner').spinner({step: function(dir){
  return dir == 'up' && this.oldValue == 0 ? 10 : 5;
}});
```
