### ISSUE TITLE
Button keeps focused and number won't stop growing.

### ISSUE THREAD

**Issue by ghaschel** [xixilive/jquery-spinner#14]
When the mouse is moved out of the element, and then released, the button element keep focused, then so, making the number grow until i click somewhere and remove the focus from it. :)

**Comment by ghaschel** [comment]
If i make a button focused, and then (before clicking anywhere else in the page) make another button focused, both of them keep growing.

**Comment by xixilive** [comment]
SOLUTION 1:
DO NOT use a hyper-link as the arrow buttons;

```html
<a style="cursor:pinter;" data-spin="up">-</a>
<a style="cursor:pinter;" data-spin="down">-</a>
```

SOLUTION 2:
to prevent the dragstar event on arrow buttons:

```
<a href="javascript:;" data-spin="down" ondragstart="return false;">-</a>
```
