### ISSUE TITLE
Rails turbolinks 支持有问题？

### ISSUE THREAD

**Issue by xiajian** [xixilive/jquery-spinner#16]
启用 Rails turbolinks 之后，从其他页面的点击进入包含 spinner 功能的页面中，点击 + 或 -，加减有时是 2，3，4等的，单击事件被执行了多次，请问如何处理?? ？

**Comment by xixilive** [comment]
jquery.spinner使用默认的selector
```
$('[data-trigger="spinner"]')
```
来初始化插件, 可以通过不使用默认的selector来自定义插件初始化, 比如:
```
// jquery.spinner.js#L219
$(document).on('page:load', function(){
   $('.myspinner').spinner();
});
```

**Comment by xiajian** [comment]
恩，谢谢。最后发现，turbolinks 坑太多了，我把 turbolinks 去掉了。
