### ISSUE TITLE
cannot set parameters repetitively

### ISSUE THREAD

**Issue by xiaok1988** [xixilive/jquery-spinner#20]
Hi all,
I used jquery-spinner in my company project and just found it cannot support setting parameters repetitively. I.e., if i set the input attributes such as data-max = "100", data-min="1", data-step="1" in the html page , and then change it through jquery using $("#spinner").attr("data-max", 10);  $("#spinner").attr("data-min", 1);  $("#spinner").attr("data-step", 0.1); then it just didnot work. Is there anything wrong with my code? Or is it simply a bug in the project?

Thanks

**Comment by xixilive** [comment]
You should init these DATA attributes before you setup a spinner instance

```
$('#spinner')
  .attr('data-max', 10)
  // whatever attrs
  .spinner(SOME_OPTIONS);
```
