### ISSUE TITLE
2 spinners on a single page does not work

### ISSUE THREAD

**Issue by kekemeke** [xixilive/jquery-spinner#23]
Hello, i have a little problem with ur spinner, this about 2 spinners on a single page. First spinner works well, but second one nope, and i dont known why :(.
First spinner - http://prntscr.com/8wn3c0 (works fine)
The second spinner appears after opening pop-up - http://prntscr.com/8wn5h2 (doesn`t work)
I can give you a link to my site, where the problem has occurred.

Thanks.
P.S.
Sry for my bad English :<

**Comment by xixilive** [comment]
could you check your jquery-selector returns the correct elements? It works for multiple instance in one document scope, some examples at https://github.com/xixilive/jquery-spinner
